// Generated by CoffeeScript 1.3.3
(function() {
  var JangaSlideshow;

  JangaSlideshow = (function() {

    JangaSlideshow.totalSlides = 0;

    JangaSlideshow.slideInterval = null;

    function JangaSlideshow() {
      var _this = this;
      $('.change-slide:first').addClass('slide-current');
      this.countSlides();
      this.bindNavClick();
      this.bindMouseEvents();
      this.slideInterval = setInterval(function() {
        return _this.autoMoveSlides();
      }, 5000);
    }

    JangaSlideshow.prototype.countSlides = function() {
      var i;
      i = 0;
      $('.change-slide').each(function() {
        return i += 1;
      });
      return this.totalSlides = i;
    };

    JangaSlideshow.prototype.changeSlide = function(index) {
      $('#slide-frame').animate({
        top: "" + (65 * index) + "px"
      }, 500);
      $('.slides').animate({
        top: "-" + (260 * index) + "px"
      }, 500);
      return this;
    };

    JangaSlideshow.prototype.autoMoveSlides = function() {
      var element, index, nextElement;
      if (this.totalSlides <= 1) {
        clearInterval(this.slideInterval);
      }
      element = $('.slide-current').parents('.nav-item');
      if (element == null) {
        clearInterval(this.slideInterval);
      }
      nextElement = $(element).next();
      index = $(element).next().children('.change-slide').attr('rel');
      if (index == null) {
        nextElement = $('.nav-item:first');
        index = 0;
      }
      $('.change-slide').removeClass('slide-current');
      $(nextElement).children('.change-slide').addClass('slide-current');
      return this.changeSlide(index);
    };

    JangaSlideshow.prototype.bindNavClick = function() {
      var _this = this;
      $('.change-slide').on('click', function(event) {
        var index;
        event.preventDefault();
        $('.change-slide').removeClass('slide-current');
        $(_this).parent().addClass('slide-current');
        index = $(event.target).parent().attr('rel');
        return _this.changeSlide(index);
      });
      return this;
    };

    JangaSlideshow.prototype.bindMouseEvents = function() {
      var _this = this;
      $('.wgt-slideshow').on({
        mouseenter: function() {
          return clearInterval(_this.slideInterval);
        },
        mouseleave: function() {
          return _this.slideInterval = setInterval(function() {
            return _this.autoMoveSlides();
          }, 5000);
        }
      });
      return this;
    };

    return JangaSlideshow;

  })();

  $(function() {
    var slideShow;
    return slideShow = new JangaSlideshow();
  });

}).call(this);
