// Generated by CoffeeScript 1.3.3
var Cliente, Funcionario;

Cliente = function(nome, email) {
  if (!(this instanceof Cliente)) {
    return new Cliente(nome, email);
  }
  this.nome = nome;
  this.email = email;
  this.init.apply(this, arguments);
  return this;
};

Cliente.prototype = {
  init: function() {},
  getDados: function() {
    return "Nome: " + this.nome + ", Email" + this.email;
  }
};

Funcionario = function(nome, matricula) {
  if (!(this instanceof Funcionario)) {
    return new Funcionario(nome, matricula);
  }
  this.nome = nome;
  this.matricula = matricula;
  return this;
};

Funcionario.prototype = {
  init: function() {
    if (this.nome === null) {
      throw Exception('Nome não informado');
    }
  },
  getDados: function() {
    return "Nome: " + this.nome + ", Matrícula: " + this.matricula;
  }
};
